### ISSUE TITLE
color-contrast

### ISSUE THREAD

**Issue by jensgro** [phpMyFAQ/legacy.phpmyfaq.de#1]
Die Variable @color-2 sollte z.B. #c74410 sein, zumindest bei den Links. Denn der Farbkontrast ist recht niedrig. Da dieser Farbwert allerdings überall im Design genommen wird, scheue ich mich davor, den Wert einfach zu ändern. Vielleicht sollten wir am Ende einfach noch einen Durchgang mit Farbkontrasten machen.

**Comment by thorsten** [comment]
Links könnte man ja mit darken() dunkler machen?

**Comment by jensgro** [comment]
Klar. Aber ich würde gerne die Farben möglichst gut treffen. Aber Du hast Recht. Das wäre ien guter Kompromiss.
