### ISSUE TITLE
Social Buttons sind sehr schlecht für Performance

### ISSUE THREAD

**Issue by jensgro** [phpMyFAQ/legacy.phpmyfaq.de#2]
Die Social-Buttons im oberen Bereich der Startseite sind sehr schlecht für die Performance und die einzige Quelle für Validierungsfehler. Es gibt überarbeitete Varianten, die ohne iframe arbeiten. Haben die überhaupt einen messbaren Nutzen? Smashingmagazine hatte sie abgeschafft, wegen der Performance und weil sie keinen erkennbaren Nutzen für sie hatten.

**Comment by thorsten** [comment]
Stimmt schon, da sollten bessere rein

**Comment by jensgro** [comment]
Oder gar keine :-)

**Comment by thorsten** [comment]
Evtl Twitter und Facebook raus und die Github Buttons auf die Developmentseite?

**Comment by jensgro** [comment]
Du hast doch im Footer alle Links zu Github, Twitter und Fratzenbuch. Wer Dich auf Github finden will, der schafft das schon über den Footer. Oder er ist nicht intelligent genug :-)
