### ISSUE TITLE
Question: use Markdown editor instead of TinyMCE?

### ISSUE THREAD

**Issue by jerry1970** [phpMyFAQ/legacy.phpmyfaq.de#8]
Hi,

Is it possible to let authors of FAQ articles use a Markdown editor (or even a plain text editor but with a Markdown parser at the front-end) instead of TinyMCE? All authors tend to use different layouts and styles, etc. TinyMCE uses way too specific HTML styling which looks outdated and rather ugly, but most of all it's a pain to change when the designer decides to change the way the site looks.

I could remove most buttons from the TinyMCE toolbar and only let the editors select a style, but TinyMCE still adds too much HTML clutter.

Thanks!

**Comment by thorsten** [comment]
Please add this feature request here: https://github.com/thorsten/phpMyFAQ/issues
